FROM python:3-alpine3.15

RUN apt-get update \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


WORKDIR /app
COPY . /app

RUN pip install flask
RUN pip install requests
RUN pip install docker

EXPOSE 9090
CMD python ./fs.py

FROM python:3.9


